name: /mnt/P41/Repositories/LinearDesign/.conda
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.41.2=h2797004_1
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.0=hd590300_3
  - perl=5.32.1=2_h7f98852_perl5
  - pip=23.1.2=pyhd8ed1ab_0
  - python=3.9.16=h2782a2a_0_cpython
  - python_abi=3.9=3_cp39
  - readline=8.2=h8228510_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - attrs==23.1.0
      - biopython==1.81
      - click==8.1.3
      - fastjsonschema==2.16.3
      - jsonschema==4.17.3
      - jupyter-core==5.3.0
      - nbformat==5.8.0
      - numpy==1.24.3
      - pandas==2.0.1
      - platformdirs==3.5.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - scipy==1.10.1
      - six==1.16.0
      - traitlets==5.9.0
      - tzdata==2023.3
      - viennarna==2.5.0a5
prefix: /mnt/P41/Repositories/LinearDesign/.conda
